language: c
sudo: false

before_script:
    - curl -O http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
    - tar -xzf SDL2-2.0.3.tar.gz
    - (cd SDL2-2.0.3 && ./configure && make && sudo make install)

script: sh ./cibuild.sh

